// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: artist_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArtistClient is the client API for Artist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtistClient interface {
	GetArtist(ctx context.Context, in *ArtistRequest, opts ...grpc.CallOption) (*ArtistResponse, error)
	SearchArtists(ctx context.Context, in *SearchArtistRequest, opts ...grpc.CallOption) (*ArtistListResponse, error)
}

type artistClient struct {
	cc grpc.ClientConnInterface
}

func NewArtistClient(cc grpc.ClientConnInterface) ArtistClient {
	return &artistClient{cc}
}

func (c *artistClient) GetArtist(ctx context.Context, in *ArtistRequest, opts ...grpc.CallOption) (*ArtistResponse, error) {
	out := new(ArtistResponse)
	err := c.cc.Invoke(ctx, "/pb.Artist/GetArtist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistClient) SearchArtists(ctx context.Context, in *SearchArtistRequest, opts ...grpc.CallOption) (*ArtistListResponse, error) {
	out := new(ArtistListResponse)
	err := c.cc.Invoke(ctx, "/pb.Artist/SearchArtists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtistServer is the server API for Artist service.
// All implementations must embed UnimplementedArtistServer
// for forward compatibility
type ArtistServer interface {
	GetArtist(context.Context, *ArtistRequest) (*ArtistResponse, error)
	SearchArtists(context.Context, *SearchArtistRequest) (*ArtistListResponse, error)
	mustEmbedUnimplementedArtistServer()
}

// UnimplementedArtistServer must be embedded to have forward compatible implementations.
type UnimplementedArtistServer struct {
}

func (UnimplementedArtistServer) GetArtist(context.Context, *ArtistRequest) (*ArtistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArtist not implemented")
}
func (UnimplementedArtistServer) SearchArtists(context.Context, *SearchArtistRequest) (*ArtistListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchArtists not implemented")
}
func (UnimplementedArtistServer) mustEmbedUnimplementedArtistServer() {}

// UnsafeArtistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtistServer will
// result in compilation errors.
type UnsafeArtistServer interface {
	mustEmbedUnimplementedArtistServer()
}

func RegisterArtistServer(s grpc.ServiceRegistrar, srv ArtistServer) {
	s.RegisterService(&Artist_ServiceDesc, srv)
}

func _Artist_GetArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServer).GetArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Artist/GetArtist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServer).GetArtist(ctx, req.(*ArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Artist_SearchArtists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServer).SearchArtists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Artist/SearchArtists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServer).SearchArtists(ctx, req.(*SearchArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Artist_ServiceDesc is the grpc.ServiceDesc for Artist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Artist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Artist",
	HandlerType: (*ArtistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArtist",
			Handler:    _Artist_GetArtist_Handler,
		},
		{
			MethodName: "SearchArtists",
			Handler:    _Artist_SearchArtists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "artist_service.proto",
}
