// Code generated by ent, DO NOT EDIT.

package playlistsong

import (
	"time"
)

const (
	// Label holds the string label denoting the playlistsong type in the database.
	Label = "playlist_song"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlaylistID holds the string denoting the playlist_id field in the database.
	FieldPlaylistID = "playlist_id"
	// FieldSongID holds the string denoting the song_id field in the database.
	FieldSongID = "song_id"
	// FieldDateAdded holds the string denoting the date_added field in the database.
	FieldDateAdded = "date_added"
	// EdgePlaylist holds the string denoting the playlist edge name in mutations.
	EdgePlaylist = "playlist"
	// EdgeSong holds the string denoting the song edge name in mutations.
	EdgeSong = "song"
	// Table holds the table name of the playlistsong in the database.
	Table = "playlist_songs"
	// PlaylistTable is the table that holds the playlist relation/edge.
	PlaylistTable = "playlist_songs"
	// PlaylistInverseTable is the table name for the Playlist entity.
	// It exists in this package in order to avoid circular dependency with the "playlist" package.
	PlaylistInverseTable = "playlists"
	// PlaylistColumn is the table column denoting the playlist relation/edge.
	PlaylistColumn = "playlist_id"
	// SongTable is the table that holds the song relation/edge.
	SongTable = "playlist_songs"
	// SongInverseTable is the table name for the Song entity.
	// It exists in this package in order to avoid circular dependency with the "song" package.
	SongInverseTable = "songs"
	// SongColumn is the table column denoting the song relation/edge.
	SongColumn = "song_id"
)

// Columns holds all SQL columns for playlistsong fields.
var Columns = []string{
	FieldID,
	FieldPlaylistID,
	FieldSongID,
	FieldDateAdded,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDateAdded holds the default value on creation for the "date_added" field.
	DefaultDateAdded func() time.Time
)
