// Code generated by ent, DO NOT EDIT.

package like

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sentrionic/horizon/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// SongID applies equality check predicate on the "song_id" field. It's identical to SongIDEQ.
func SongID(v uuid.UUID) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSongID), v))
	})
}

// DateAdded applies equality check predicate on the "date_added" field. It's identical to DateAddedEQ.
func DateAdded(v time.Time) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDateAdded), v))
	})
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUserID), v))
	})
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Like {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUserID), v...))
	})
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Like {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUserID), v...))
	})
}

// SongIDEQ applies the EQ predicate on the "song_id" field.
func SongIDEQ(v uuid.UUID) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSongID), v))
	})
}

// SongIDNEQ applies the NEQ predicate on the "song_id" field.
func SongIDNEQ(v uuid.UUID) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSongID), v))
	})
}

// SongIDIn applies the In predicate on the "song_id" field.
func SongIDIn(vs ...uuid.UUID) predicate.Like {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSongID), v...))
	})
}

// SongIDNotIn applies the NotIn predicate on the "song_id" field.
func SongIDNotIn(vs ...uuid.UUID) predicate.Like {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSongID), v...))
	})
}

// DateAddedEQ applies the EQ predicate on the "date_added" field.
func DateAddedEQ(v time.Time) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDateAdded), v))
	})
}

// DateAddedNEQ applies the NEQ predicate on the "date_added" field.
func DateAddedNEQ(v time.Time) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDateAdded), v))
	})
}

// DateAddedIn applies the In predicate on the "date_added" field.
func DateAddedIn(vs ...time.Time) predicate.Like {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDateAdded), v...))
	})
}

// DateAddedNotIn applies the NotIn predicate on the "date_added" field.
func DateAddedNotIn(vs ...time.Time) predicate.Like {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDateAdded), v...))
	})
}

// DateAddedGT applies the GT predicate on the "date_added" field.
func DateAddedGT(v time.Time) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDateAdded), v))
	})
}

// DateAddedGTE applies the GTE predicate on the "date_added" field.
func DateAddedGTE(v time.Time) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDateAdded), v))
	})
}

// DateAddedLT applies the LT predicate on the "date_added" field.
func DateAddedLT(v time.Time) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDateAdded), v))
	})
}

// DateAddedLTE applies the LTE predicate on the "date_added" field.
func DateAddedLTE(v time.Time) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDateAdded), v))
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSong applies the HasEdge predicate on the "song" edge.
func HasSong() predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SongTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SongTable, SongColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSongWith applies the HasEdge predicate on the "song" edge with a given conditions (other predicates).
func HasSongWith(preds ...predicate.Song) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SongInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SongTable, SongColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Like) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Like) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Like) predicate.Like {
	return predicate.Like(func(s *sql.Selector) {
		p(s.Not())
	})
}
